#!/usr/bin/python3

import os
import sys
import shutil
import os.path
import argparse
import subprocess


if shutil.which("lli") is not None:
    # MacOS
    EXT = ""
elif shutil.which("lli-7") is not None:
    # Debian
    EXT = "-7"
else:
    print("Error: unable to locate LLVM command line program \"lli\".  Please ensure that the LLVM 7 tools are included in your $PATH")
    sys.exit(-1)

RM = "rm"
BUILD = "cargo build"
COMPILE = "cargo run --"
MOLFLAGS = "-O3"
LINK = "clang"
LDFLAGS = "-lc -lm -lgc -no-pie"
ILINK = "llvm-link" + EXT
IRUN = "lli" + EXT


def main():
    parser = argparse.ArgumentParser(prog='molten', formatter_class=argparse.ArgumentDefaultsHelpFormatter, description='Simple build script for molten programs')
    parser.add_argument('-f', '--force', action='store_true', help='Force a recompile of all files')
    parser.add_argument('-d', '--debug', action='store_true', help='Run the compiler with debugging on')
    subparsers = parser.add_subparsers()

    def add_build_args(cmd):
        cmd.add_argument('-S', '--assembly', action='store_true', help='Compile to assembly and use the interpreter')
        cmd.add_argument('-o', '--output', type=str, help='Output file name')

    cmd = subparsers.add_parser("build", help="compile a single file program")
    add_build_args(cmd)
    cmd.add_argument("filename")
    cmd.set_defaults(command=command_build)

    cmd = subparsers.add_parser("run", help="compile and run a single file program")
    add_build_args(cmd)
    cmd.add_argument("filename")
    cmd.set_defaults(command=command_run)

    cmd = subparsers.add_parser("clean", help="delete all generated files")
    cmd.add_argument("directory", nargs='?', default=".")
    cmd.set_defaults(command=command_clean)

    cmd = subparsers.add_parser("cleanall", help="delete all generated files including from all subdirectories")
    cmd.add_argument("directory")
    cmd.set_defaults(command=command_cleanall)

    args = parser.parse_args()
    if 'command' not in args:
        parser.print_help()
    else:
        try:
            args.command(args)
        except Exception as e:
            sys.stderr.write("Command failed: " + str(e) + "\n")
            sys.exit(-1)


def command_build(args):
    target = args.output if args.output else os.path.splitext(args.filename)[0]
    if args.assembly:
        target += ".bc"
    flags = MOLFLAGS
    flags += " -d" if args.debug else ""
    compile_and_link(target, [ "lib/libcore.mol", args.filename ], flags=flags, args=args)
    return target

def command_run(args):
    target = command_build(args)
    if args.assembly:
        runordie(IRUN + " " + target)
    else:
        runordie("./{}".format(target))

def command_clean(args):
    os.system("cd {dir} && {rm} *.ll *.dec *.bc *.o *.bin".format(dir=args.directory, rm=RM))

def command_cleanall(args):
    for (basedir, dirnames, filenames) in os.walk(args.directory):
        for filename in filenames:
            if any(filename.endswith(ext) for ext in [ ".bc", ".ll", ".dec", ".o", ".bin" ]):
                path = os.path.join(basedir, filename)
                print("Deleting " + path)
                os.unlink(path)



def compile_and_link(target, deps, flags, args):
    compiled = [ ]
    main = deps.pop()
    for dep in deps:
        compiled.append(compile(dep, flags=(flags + " -l"), force=args.force, assembly=args.assembly))
    compiled.append(compile(main, flags=flags, force=args.force, assembly=args.assembly))
    link(target, compiled, args.assembly)


def compile(filename, flags="", force=False, assembly=False):
    target = os.path.splitext(filename)[0] + (".o" if not assembly else ".ll")
    flags += " -c" if not assembly else " -S --no-gc"
    if force or not os.path.exists(target) or os.path.getmtime(filename) > os.path.getmtime(target):
        runordie("{compile} {flags} {filename}".format(compile=COMPILE, flags=flags, filename=filename))
    return target

def link(target, filenames, assembly=False):
    if not assembly:
        runordie("{ld} {flags} -o {target} {files}".format(ld=LINK, flags=LDFLAGS, target=target, files=" ".join(filenames)))
    else:
        runordie("{ld} {files} > {target}".format(ld=ILINK, files=" ".join(filenames), target=target))


def runcmd(cmd):
    #print(cmd)
    result = subprocess.run(cmd, shell=True)
    return result.returncode

def runordie(cmd):
    #print(cmd)
    result = subprocess.run(cmd, shell=True)
    if result.returncode != 0:
        raise Exception("{} exited with code {}".format(cmd, result.returncode))



if __name__ == "__main__":
    main()

